version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
#    volumes:
#    - ./data:/data/db
    ports:
    - "27017:27017"
  api:
    build:
      context: ./api/
    command: node app.js
    volumes:
    - ./api/:/usr/app
    - /usr/app/node_modules
    ports:
    - "8080:8080"
    environment:
    - NODE_ENV=development
    - CHOKIDAR_USEPOLLING=true
    depends_on:
    - mongo
  react-client:
    build:
      context: ./react-client/
    command: npm start
    volumes:
    - ./react-client/:/usr/app
    - /usr/app/node_modules
    depends_on:
    - api
    ports:
    - "3000:3000"